spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: happyride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}:8433/happyride-dispatch
    username: happyride-dispatch-user
    password: happyride-dispatch-password
  redis:
    url: redis://${DOCKER_HOST_IP:localhost}:6379
  flyway:
    schemas:
      - happyride
axon:
  axonserver:
    servers: ${DOCKER_HOST_IP:localhost}:8124
  serializer:
    events: jackson
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:29092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181
