server:
  port: 8504
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: happyride
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}:8435/happyride-payment
    username: postgres
    password: postgres
  flyway:
    schemas:
      - happyride
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:29092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181